# CI de nivel 01 - disparo manual a partir de um clique

#nome do nosso pipeline
nane: 'Execução Manual'

#regras de disparos (gatilho/triggers)
#gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

  #trabalho/ tarefas que são feitos dentro dos pipelnes = jobs
jobs: 
    e2e-tests:

    #maquina que o job vai executar
      runs-on: ubuntu-latest

      #passo a passo do job
      steps:
        #clone do projeto
        - uses: actions/checkout@v4

        #instalação do node
        - uses: actions/setup-node@v4
          with:
            node-version: latest

        #instalação do yarn
        - name: Instalando Yarn
        - run: npm install -g yarn

        #instalação das dependências    
        - name: Instalando Dependências
        - run: yarn install

        #instalacao do Playwright
        - name: Instalando Playwright
        - run: yarn playwright install

        #execução dos testes e2e
        - name: Execução dos Testes E2E
        - run: yarn run e2e