# CI de nível 03 - disparo após conclusão de uma pipeline

# nome do nosso pipeline
name: 'Execução por Deploy'

# regras de disparos (gatilho/triggers)
# gatilho de exec manual = workflow_dispatch
# gatilho de exec agendada = schedule
# gatilho de exec a partir de outro pipe = workflow_run   workflow_dispatch
on:
  workflow_run: 
    workflows: ["Execução Manual"]
    types: 
      - completed

# trabalho/tarefas que são feitos dentro dos pipelines = jobs
jobs: 
  e2e-tests:
    # máquina que o job vai executar
    runs-on: ubuntu-latest

    # passo a passo do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências    
      - name: Instalando Dependências
        run: yarn install

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # execução dos testes e2e
      - name: Execução dos Testes E2E
        run: yarn run e2e
